#!/bin/bash

## Description: Open the current project in a container in VSCode
## Usage: code [-d|--database]
## Example: ddev code

CODE_EXECUTABLE="code"

case ${1:-} in
-d | -db | --database)
    CODE_CONTAINER="ddev-${DDEV_PROJECT}-db"
    CODE_PATH=$HOME
    ;;
--) # End of all options.
    ;;
-?*)
    printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
    ;;
*) # Default case
    CODE_CONTAINER="ddev-${DDEV_PROJECT}-web"
    CODE_PATH=/var/www/html
    ;;
esac

if [[ ${CODE_CONTAINER+x} ]]; then
    ${CODE_EXECUTABLE} --folder-uri "vscode-remote://attached-container+$(printf "$CODE_CONTAINER" | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')${CODE_PATH}"
fi