baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Foundation Craft DDEV'
primary: true
siteGroup: 6d2d155d-1851-46ba-b63d-6910b5e99b8b # Foundation Craft DDEV
sortOrder: 1
